[build]
  publish = "customActivity"
  command = "# no build command needed"
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://*.exacttarget.com https://*.marketingcloudapps.com https://*.force.com"
    X-Frame-Options = "ALLOW-FROM https://*.marketingcloudapps.com"